version: '3.7'

services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - PGDATA=$HOME/postgresql/data
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
      - ./sql-script/:/docker-entrypoint-initdb.d/
  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: postgres
      DB_SCHEMA: keycloak
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Admin@dmin
    ports:
      - 8080:8080
    depends_on:
      - postgres